# Generated by Django 6.0.1 on 2026-01-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoneymate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='id',
        ),
        migrations.AddField(
            model_name='expense',
            name='Eid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
