# Generated by Django 6.0.1 on 2026-01-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoneymate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(default='', max_length=80),
        ),
    ]
